//
//  AccountWorker.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 30/04/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AccountWorker: UserPersistenceInjected, GeneralPersistenceInjected {
    
    /// Fetch user in database
    ///
    /// - Returns: return a user if found else nil
    func getUser() -> (user: User?, error: PersistenceErrors?) {
        return userDataManager.getUser()
    }
    
    /// Delete all database information
    ///
    /// - Returns: nil if everything when well or and error otherwise
    func deleteUser() -> PersistenceErrors? {
        return generalDataManager.deleteData()
    }
}
