language: objective-c
osx_image: xcode9

cache:
- bundler
- cocoapods

-env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - bundle install
 # - pod install --repo-update
   - pod repo update
  - chmod +x travis/tests_script.sh

script:
- ./Pods/SwiftLint/swiftlint --reporter junit
- travis/tests_script.sh
- bundle exec danger

after_success:
  - bash <(curl -s https://codecov.io/bash)
