language: objective-c
cache: cocoapods
osx_image: xcode9

before_install:
  - gem install xcov --no-ri --no-rdoc --no-document
  - gem install fastlane --no-ri --no-rdoc --no-document

jobs:
  include:
    - stage: Swiflint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: XCTest
      script:
        - travis/unit_test_script.sh

    - stage: XCTest
      script:
        - travis/ui_test_script.sh

    - stage: Coverage
      script:
        - travis/report_test_coverage.sh
