language: objective-c
cache: cocoapods
osx_image: xcode9

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document

jobs:
  include:
    - stage: Swiflint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: XCTest
      script:
        - fastlane scan -s PeeCheckTests

    - stage: XCTest
      script:
        - fastlane scan -s PeeCheckUITests