language: objective-c
osx_image: xcode9

cache:
- bundler
- cocoapods

-env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - bundle update
  - bundle install
  - gem install xcpretty
  - pod repo update
  - chmod +x travis/tests_script.sh

script:
- set -o pipefail
- ./Pods/SwiftLint/swiftlint --reporter junit
- travis/tests_script.sh
- bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash)
