language: objective-c
cache: cocoapods
osx_image: xcode9

-env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install cocoapods
  - pod install --repo-update
  - gem install xcov --no-ri --no-rdoc --no-document
  - gem install fastlane --no-ri --no-rdoc --no-document
  - chmod +x travis/tests_script.sh
  - chmod +x travis/report_test_coverage.sh

jobs:
  include:
    - stage: Swiflint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: XCTest
      script:
        - travis/tests_script.sh

    - stage: Coverage
      script:
        - travis/report_test_coverage.sh
