//
//  MainResultsPresenterTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 11/03/2019.
//  Copyright (c) 2019 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PeeCheck
import XCTest

//class MainResultsPresenterTests: XCTestCase {
//  // MARK: Subject under test
//  
//  var sut: MainResultsPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp() {
//    super.setUp()
//    setupMainResultsPresenter()
//  }
//  
//  override func tearDown() {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMainResultsPresenter() {
//    sut = MainResultsPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class MainResultsDisplayLogicSpy: MainResultsDisplayLogic {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: MainResults.Something.ViewModel) {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething() {
//    // Given
//    let spy = MainResultsDisplayLogicSpy()
//    sut.viewController = spy
//    let response = MainResults.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
