//
//  MainResultsWorkerTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 11/03/2019.
//  Copyright (c) 2019 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PeeCheck
import XCTest

//class MainResultsWorkerTests: XCTestCase {
//  // MARK: Subject under test
//  
//  var sut: MainResultsWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp() {
//    super.setUp()
//    setupMainResultsWorker()
//  }
//  
//  override func tearDown() {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMainResultsWorker() {
//    sut = MainResultsWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething() {
//    // Given
//    
//    // When
//    
//    // Then
//  }
//}
