//
//  ChartsPresenterTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 05/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Quick
import Nimble
@testable import PeeCheck

class ChartsPresenterTests: QuickSpec {
    
    override func spec() {
        describe("ChartsPresenter tests") {
            
            // MARK: Subject under test
            
            var sut: ChartsPresenter!
            
            beforeSuite {
                setupAccountPresenter()
            }
            
            // MARK: Test setup
            
            func setupAccountPresenter()
            {
                sut = ChartsPresenter()
            }
            
            // MARK: Test doubles
            
            class ChartsDisplayLogicSpy: ChartsDisplayLogic {
                var displayChartsViewCalled = false
                
                func displayChartsView(viewModel: Charts.FetchChartsViews.ViewModel) {
                    displayChartsViewCalled = true
                }
            }
            
            // MARK: Tests
            
            context("Display View controller") {
                it("Should display ") {
                    let viewControllers = ["test": UIViewController()]
                    let spy = ChartsDisplayLogicSpy()
                    sut.viewController = spy
                    let response = Charts.FetchChartsViews.Response(viewControllers: viewControllers)
                    
                    sut.presentFetchChartsViews(response: response)
                    expect(spy.displayChartsViewCalled).to(beTrue())
                }
            }
        }
    }
}
