//
//  AccountWorkerTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 01/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Quick
import Nimble
@testable import PeeCheck

class AccountWorkerTests: QuickSpec {
    
    override func spec() {
        describe("AccountWorker tests") {
            
            // MARK: Subject under test
            
            var sut: AccountWorker!
            
            beforeSuite {
                setupAccountWorker()
            }
            
            // MARK: Test setup
            
            func setupAccountWorker() {
                sut = AccountWorker()
            }
            
            // MARK: Tests
            
            context("Get user information") {
                it("Sould return nil when no user was found") {
                    expect(sut.getUser()).to(beNil())
                }
            }
            
            context("Delete user information") {
                it("Sould return nil if no error occured") {
                    expect(sut.deleteUser()).to(beNil())
                }
            }
        }
    }
}
