//
//  ChartsInteractor.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 10/06/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsBusinessLogic {
  func fetchChartsViews(request: Charts.FetchChartsViews.Request)
}

protocol ChartsDataStore {
  //var name: String { get set }
}

class ChartsInteractor: ChartsBusinessLogic, ChartsDataStore {
  var presenter: ChartsPresentationLogic?
  var worker = ChartsWorker()
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchChartsViews(request: Charts.FetchChartsViews.Request) {
    worker = ChartsWorker()
    
    let response = Charts.FetchChartsViews.Response(viewControllers: worker.getChartsViews())
    presenter?.presentFetchChartsViews(response: response)
  }
}
