//
//  ChartsWorker.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 10/06/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChartsWorker {
    func getChartsViews() -> [String: UIViewController] {
        var viewControllers: [String: UIViewController] = [:]
        
//        viewControllers["main"] = MainResultsViewController()
        viewControllers["charts"] = AccountViewController()
        
        return viewControllers
    }    
}
