//
//  ChartsPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 10/06/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsPresentationLogic
{
  func presentSomething(response: Charts.Something.Response)
}

class ChartsPresenter: ChartsPresentationLogic
{
  weak var viewController: ChartsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Charts.Something.Response)
  {
    let viewModel = Charts.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
