//
//  ChartsPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 10/06/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsPresentationLogic: class {
  func presentFetchChartsViews(response: Charts.FetchChartsViews.Response)
}

final class ChartsPresenter: ChartsPresentationLogic {
  weak var viewController: ChartsDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchChartsViews(response: Charts.FetchChartsViews.Response) {
    
    var displayedViewControllers: [Charts.FetchChartsViews.ViewModel.DisplayedView] = []    
    for (name, viewC) in response.viewControllers {
        let name = name
        let viewC = viewC
        let displayedViewController = Charts.FetchChartsViews.ViewModel.DisplayedView(name: name, viewController: viewC)
        displayedViewControllers.append(displayedViewController)
    }
    
    displayedViewControllers = displayedViewControllers.sorted(by: { $0.name > $1.name })

    let viewModel = Charts.FetchChartsViews.ViewModel(displayedViewControllers: displayedViewControllers)
    viewController?.displayChartsView(viewModel: viewModel)
  }
}
