//
//  ChartsInteractor.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 10/06/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsBusinessLogic: class {
    func fetchChartsViews(request: Charts.FetchChartsViews.Request)
}

protocol ChartsDataStore {
    var viewControllers: [String: UIViewController] { get set }
}

final class ChartsInteractor: ChartsBusinessLogic, ChartsDataStore {
    var viewControllers: [String: UIViewController] = [:]
    var presenter: ChartsPresentationLogic?
    var worker = ChartsWorker()
    
    // MARK: Do something
    
    func fetchChartsViews(request: Charts.FetchChartsViews.Request) {
        if viewControllers.isEmpty {
            viewControllers = worker.getChartsViews()
        }
//        worker = ChartsWorker()
        
        let response = Charts.FetchChartsViews.Response(viewControllers: viewControllers)
        presenter?.presentFetchChartsViews(response: response)
    }
}
