//
//  CreateUserWorkerTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 08/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Quick
import Nimble
@testable import PeeCheck

class CreateUserWorkerTests: QuickSpec {
    
    override func spec() {
        describe("CreateUserWorker tests") {
            
            // MARK: Subject under test
            
            var sut: CreateUserWorker!
            
            beforeSuite {
                setupCreateUserWorker()
            }
            
            // MARK: Test setup
            
            func setupCreateUserWorker() {
                sut = CreateUserWorker()
            }
            
            // MARK: Tests
            
            context("User creation") {
                it("Sould return a user if no error occured") {
                    let userFields = CreateUser.UserFields(age: 24, gender: .woman)
                    let user = sut.createUser(userFields)
                    expect(user).to(beAKindOf(User.self))
                    expect(user?.age) == 24
                    expect(user?.gender) == .woman
                }
            }
        }
    }
}

