//
//  CreateUserPresenterTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 08/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//@testable import PeeCheck
//import XCTest
//
//class CreateUserPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: CreateUserPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupCreateUserPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupCreateUserPresenter()
//  {
//    sut = CreateUserPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class CreateUserDisplayLogicSpy: CreateUserDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: CreateUser.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = CreateUserDisplayLogicSpy()
//    sut.viewController = spy
//    let response = CreateUser.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
