//
//  RecordingModels.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 06/04/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Recording {
    
    // MARK: Use cases
    
    enum SetSwitch {
        struct Request {
        }
        struct Response {
           var isNight: Bool
        }
        struct ViewModel {
            var isNight: Bool
        }
    }
    
    enum RecordMicturition {
        struct Request {
        }
        struct Response {
            var isRecording: Bool
            var savedMicturition: PersistenceErrors?
        }
        struct ViewModel {
            var isRecording: Bool
            var error: PersistenceErrors?
        }
    }
}
