//
//  RecordingInteractor.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 06/04/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecordingBusinessLogic {
  func doSomething(request: Recording.Something.Request)
}

protocol RecordingDataStore {
  //var name: String { get set }
}

class RecordingInteractor: RecordingBusinessLogic, RecordingDataStore {
  var presenter: RecordingPresentationLogic?
  var worker: RecordingWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Recording.Something.Request) {
    worker = RecordingWorker()
    worker?.doSomeWork()
    
    let response = Recording.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
