//
//  RecordingPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 06/04/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecordingPresentationLogic {
  func presentSomething(response: Recording.Something.Response)
}

class RecordingPresenter: RecordingPresentationLogic {
  weak var viewController: RecordingDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Recording.Something.Response) {
    let viewModel = Recording.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
