//
//  RecordingPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 06/04/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecordingPresentationLogic {
    func presentSetSwitch(response: Recording.SetSwitch.Response)
    func presentRecordMicturition(response: Recording.RecordMicturition.Response)
}

class RecordingPresenter: RecordingPresentationLogic {
    weak var viewController: RecordingDisplayLogic?
    
    // MARK: Set Switch viewmodel information
    
    func presentSetSwitch(response: Recording.SetSwitch.Response) {
        let viewModel = Recording.SetSwitch.ViewModel(isNight: response.isNight)
        viewController?.displaySetSwitch(viewModel: viewModel)
    }
    
    // MARK: Set recording button viewmodel information
    
    func presentRecordMicturition(response: Recording.RecordMicturition.Response) {
        let viewModel = Recording.RecordMicturition.ViewModel(isRecording: response.isRecording)
        viewController?.updateRecordBtnDisplay(viewModel: viewModel)
    }
}
