//
//  MainResultsPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainResultsPresentationLogic {
  func presentFetchUserData(response: MainResults.FetchUserData.Response)
}

class MainResultsPresenter: MainResultsPresentationLogic {
  weak var viewController: MainResultsDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchUserData(response: MainResults.FetchUserData.Response) {
    let viewModel = MainResults.FetchUserData.ViewModel()
    viewController?.displayUserData(viewModel: viewModel)
  }
}
