//
//  MainResultsInteractor.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainResultsBusinessLogic {
  func fetchUserData(request: MainResults.FetchUserData.Request)
}

protocol MainResultsDataStore {
  //var name: String { get set }
}

class MainResultsInteractor: MainResultsBusinessLogic, MainResultsDataStore {
  var presenter: MainResultsPresentationLogic?
  var worker: MainResultsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchUserData(request: MainResults.FetchUserData.Request) {
    worker = MainResultsWorker()
    
    var response: MainResults.FetchUserData.Response!
    
    guard let user = worker?.getUser().user else {
        return
    }
//    worker?.doSomeWork()
    
    response = MainResults.FetchUserData.Response()
    presenter?.presentFetchUserData(response: response)
  }
}
