//
//  MainResultsWorker.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

class MainResultsWorker: UserPersistenceInjected, MicturitionPersistenceInjected {
    
    func getUser() -> (user: User?, error: PersistenceErrors?) {
        return userDataManager.getUser()
    }
    
    func getMicturitions() -> (micturitions: Results<Micturition>?, error: PersistenceErrors?) {
        return micturitionDataManager.getMicturitions()
    }
}
