//
//  MainResultsInteractor.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainResultsBusinessLogic {
  func fetchUserData(request: MainResults.FetchUserData.Request)
}

protocol MainResultsDataStore {
  //var name: String { get set }
}

final class MainResultsInteractor: MainResultsBusinessLogic, MainResultsDataStore {
  var presenter: MainResultsPresentationLogic?
  var worker: MainResultsWorker!
  
  // MARK: Get the user's data
  
  func fetchUserData(request: MainResults.FetchUserData.Request) {
    worker = MainResultsWorker()
    
    var response: MainResults.FetchUserData.Response!
    
    let user = worker.getUser().user
    let micturitions = worker.getMicturitions().micturitions
    let enoughDaysOfRecording = worker.getNumberOfDayRecording(micturitions) > 3 ? true : false
    
    
    response = MainResults.FetchUserData.Response(user: user, enoughDaysRecording: enoughDaysOfRecording, longestMicturition: worker.getLongestMicturition(micturitions), shortestMicturition: worker.getShortesttMicturition(micturitions), averageMicturitionTime: worker.getAverageMicturitionTime(micturitions), totalNumberOfMicturition: worker.getTotalNumberOfMicturition(micturitions), averageNumberOfMicturitionDaily: worker.getAverageNumberOfMicturitionDaily(micturitions), averageNumberOfMicturitionAtNight: worker.getAverageNumberOfMicturitionAtNight(micturitions))
    presenter?.presentFetchUserData(response: response)
  }
    
    
}
