//
//  MainResultsModels.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//import UIKit
//import RealmSwift
//
//enum MainResults {
//  // MARK: Use cases
//    
//    struct MicturitionResults {
//        var isNight: Bool
//        var shortestMicturition: Int
//        var longestMicturition: Int
//        var averageMicturitionTime: Double
//        var totalNumberOfMicturition: Int
//        var averageNumberOfMicturition: Double
//        var maxNumberOfMicturition: Int
//        var minNumberOfMicturition: Int
//    }
//  
//  enum FetchUserData {
//    struct Request {}
//    
//    struct Response {
//        var user: User?
//        var enoughDaysRecording: Bool
//        var data: [MicturitionResults]
//        var conclusion: [String: String]
//    }
//    
//    struct ViewModel {
//        struct DisplayedInformation {
//            var title: String
//            var shortestMicturition: String
//            var longestMicturition: String
//            var averageMicturitionTime: String
//            var averageNumberOfMicturition: String
//            var maxNumberOfMicturition: String
//            var minNumberOfMicturition: String
//        }
//        
//        struct DisplayedConclusion {
//            var title: String
//            var helper: String
//            var conclusion: String
//        }
//        
//        var user: User?
//        var enoughDaysRecording: Bool
//        var informationToDisplay: [DisplayedInformation]
//        var conclusion: DisplayedConclusion
//    }
//  }
//}
