//
//  MainResultsModels.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum MainResults {
  // MARK: Use cases
  
  enum FetchUserData {
    struct Request {}
    
    struct Response {
        var user: User?
        var enoughDaysRecording: Bool
        var longestMicturition: Int
        var shortestMicturition: Int
        var averageMicturitionTime: Double
        var totalNumberOfMicturition: Int
        var averageNumberOfMicturitionDaily: Double
        var averageNumberOfMicturitionAtNight: Double
    }
    
    struct ViewModel {
        struct DisplayedInformation {
            var longestMicturition: String
            var shortestMicturition: String
            var averageMicturitionTime: String
            var totalNumberOfMicturition: String
            var averageNumberOfMicturitionDaily: String
            var averageNumberOfMicturitionAtNight: String
        }
        
        var user: User?
        var enoughDaysRecording: Bool
        var informationToDisplay: DisplayedInformation
    }
  }
}
