//
//  MainResultsPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainResultsPresentationLogic {
  func presentFetchUserData(response: MainResults.FetchUserData.Response)
}

class MainResultsPresenter: MainResultsPresentationLogic {
  weak var viewController: MainResultsDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchUserData(response: MainResults.FetchUserData.Response) {
    let displayedInformation = MainResults.FetchUserData.ViewModel.DisplayedInformation(
        longestMicturition: " longest mixtion is: \(response.longestMicturition)",
        shortestMicturition: " shortes mixtion is: \(response.shortestMicturition)",
        averageMicturitionTime: "Average micturition time is \(response.averageMicturitionTime)",
        totalNumberOfMicturition: "Total number of micturitions recorded is \(response.totalNumberOfMicturition)",
        averageNumberOfMicturitionDaily: "Average daily micturitions is \(response.averageNumberOfMicturitionDaily)",
        averageNumberOfMicturitionAtNight: "Average night micturition is \(response.averageNumberOfMicturitionAtNight)")
    
    let viewModel = MainResults.FetchUserData.ViewModel(user: response.user, enoughDaysRecording: response.enoughDaysRecording, informationToDisplay: displayedInformation)
    viewController?.displayUserData(viewModel: viewModel)
  }
}
