//
//  MainResultsRouter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 26/08/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//@objc protocol MainResultsRoutingLogic {
//   func goToAccountPage()
//}
//
//protocol MainResultsDataPassing {
//  var dataStore: MainResultsDataStore? { get }
//}
//
//class MainResultsRouter: NSObject, MainResultsRoutingLogic, MainResultsDataPassing {
//  weak var viewController: MainResultsViewController?
//  var dataStore: MainResultsDataStore?
//    
//    func goToAccountPage() {
//        if let tabBarController = UIApplication.shared.keyWindow?.rootViewController as? UITabBarController, let viewControllers = tabBarController.viewControllers {
//            if let index = viewControllers.index(where: { ($0 as? UINavigationController)?.viewControllers.first?.isKind(of: AccountViewController.self) ?? false}) {
//                tabBarController.selectedIndex = index
//            }
//        }
//    }
//
//}
