//
//  CreateUserInteractor.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 01/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateUserBusinessLogic {
    var genderTypes: [String] { get }
    var userToEdit: User? { get set }
    func doSomething(request: CreateUser.Something.Request)
}

protocol CreateUserDataStore {
    var genderTypes: [String] { get }
    var userToEdit: User? { get set }
}

protocol CreateOrderDataStore {
    var shippingMethods: [String] { get }
}

class CreateUserInteractor: CreateUserBusinessLogic, CreateUserDataStore {
    var presenter: CreateUserPresentationLogic?
    var worker: CreateUserWorker?
    var userToEdit: User?
    var genderTypes = [
        Gender.men.localized(),
        Gender.woman.localized()
    ]
    
    // MARK: Do something
    
    func doSomething(request: CreateUser.Something.Request) {
        worker = CreateUserWorker()
        worker?.doSomeWork()
        
        let response = CreateUser.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
