//
//  CreateUserWorker.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 01/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CreateUserWorker {
    private var dataManager: DataManager
    
    init(dataManager: DataManager) {
        self.dataManager = dataManager
    }
    
    func createUser(_ age: Int, _ gender: Gender) -> (user: User?, error: CreateUserErrors?) {
        return dataManager.saveUser(age, gender)
    }
    
    func updateUser(_ age: Int, _ gender: Gender) -> (user: User?, error: CreateUserErrors?) {
        return dataManager.updateUser(age, gender)
    }
}
