//
//  CreateUserPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 01/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateUserPresentationLogic {
    func presentUserToEdit(response: CreateUser.EditUser.Response)
    func presentUserAge(response: CreateUser.UserAge.Response)
    func presentCreateUser(response: CreateUser.CreateUser.Response)
    func presentUpdateUser(response: CreateUser.UpdateUser.Response)
    func presentCheckFormFields(response: CreateUser.ActivateSaveButton.Response)
}

class CreateUserPresenter: CreateUserPresentationLogic {
    weak var viewController: CreateUserDisplayLogic?
    
    // MARK: Present User to edit
    
    func presentUserToEdit(response: CreateUser.EditUser.Response) {
        let userToEdit = response.user
        let viewModel = CreateUser.EditUser.ViewModel(
            userFields: CreateUser.UserFields(
                age: userToEdit.age,
                gender: userToEdit.gender
            ),
            pickerRow: response.pickerRow
        )
        viewController?.displayUserToEdit(viewModel: viewModel)
    }
    
    // MARK: Present Age of user
    
    func presentUserAge(response: CreateUser.UserAge.Response) {
        let viewModel = CreateUser.UserAge.ViewModel(age: response.age, valide: response.valide)
        viewController?.displayUserAge(viewModel: viewModel)
    }
    
     // MARK: Present user creation
    
    func presentCreateUser(response: CreateUser.CreateUser.Response) {
        let viewModel = CreateUser.CreateUser.ViewModel(user: response.user, error: response.error)
        viewController?.displayCreateUser(viewModel: viewModel)
    }
    
    // MARK: Present user update
    
    func presentUpdateUser(response: CreateUser.UpdateUser.Response) {
        let viewModel = CreateUser.UpdateUser.ViewModel(user: response.user, error: response.error)
        viewController?.displayUpdateUser(viewModel: viewModel)
    }
    
    func presentCheckFormFields(response: CreateUser.ActivateSaveButton.Response) {
        let viewModel = CreateUser.ActivateSaveButton.ViewModel(valide: response.valide)
        viewController?.activateSaveUserButton(viewModel: viewModel)
    }
}
