//
//  CreateUserPresenter.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 01/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateUserPresentationLogic {
  func presentSomething(response: CreateUser.Something.Response)
}

class CreateUserPresenter: CreateUserPresentationLogic {
  weak var viewController: CreateUserDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreateUser.Something.Response) {
    let viewModel = CreateUser.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
