//
//  CreateUserModels.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 01/05/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateUser {
    
    struct UserFields {
        var age: Int?
        var gender: Gender?
    }
    
    // MARK: Use cases
    
    enum EditUser {
        struct Request {
        }
        struct Response {
            var user: User
        }
        struct ViewModel {
            var userFields: UserFields
        }
    }
    
    enum UserAge {
        struct Request {
            var age: String?
        }
        struct Response {
            var age: Int?
            var valide: Bool
        }
        struct ViewModel {
            var age: Int?
            var valide: Bool
        }
    }
    
    enum CreateUser {
        struct Request {
            var userFormFields: UserFields
        }
        struct Response {
            var user: User?
        }
        struct ViewModel {
            var user: User?
        }
    }
}
