//
//  RecordingPresenterTests.swift
//  PeeCheck
//
//  Created by Martin Lukacs on 17/04/2018.
//  Copyright (c) 2018 Martin Lukacs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PeeCheck
import XCTest

class RecordingPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: RecordingPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupRecordingPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupRecordingPresenter()
  {
    sut = RecordingPresenter()
  }
  
  // MARK: Test doubles
  
  class RecordingDisplayLogicSpy: RecordingDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Recording.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = RecordingDisplayLogicSpy()
    sut.viewController = spy
    let response = Recording.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
